name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Se activa cuando subes algo a la rama main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload with Hugo/Astro
        uses: withastro/action@v3 # Esta acción oficial de Astro hace todo por ti
        # Si usas npm, no necesitas configurar nada más aquí

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4